logging:
  level:
    com.zaxxer.hikari: TRACE
    org.springframework.jdbc: DEBUG

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/postgres/schema.sql
      data-locations: classpath:/sql/postgres/data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testDb;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;

  h2:
    console:
      enabled: true
