spring:

  sql:
    init:
      mode: always
      schema-locations: classpath:/sql/postgres/schema.sql
      data-locations: classpath:/sql/postgres/data.sql

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false
    defer-datasource-initialization: true

  datasource:
    url: jdbc:postgresql://db_track:5432/tracks_db
    username: larku
    password: larku